/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasirujikomrosi;
import aplikasikasirujikom.formProduk;
import static java.awt.Frame.MAXIMIZED_BOTH;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {
 Connection konek;
    PreparedStatement pst;
    ResultSet rst;
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        konek = aplikasikasirujikom.Koneksi.KoneksiDB();
        mulai();
        tampilWaktu();
    }
     
      public void mulai() {
        register.setEnabled(false);
        Logout.setEnabled(false);
        master.setEnabled(false);
        transaksi.setEnabled(false);
        laporan.setEnabled(false);
        txtjam.setEnabled(false);
        txttanggal.setEnabled(false);
        formlogin.setVisible(false);
        btnRegister.setEnabled(false);
        btnProduk.setEnabled(false);
        btnPelanggan.setEnabled(false);
        btnPenjualan.setEnabled(false);
    }
    
    public void tampilWaktu() {
          Thread clock = new Thread() {
            public void run() {
                for(;;) {
                    Calendar cal = Calendar.getInstance();
                    SimpleDateFormat Jam = new SimpleDateFormat("hh:mm:ss");
                    SimpleDateFormat Tanggal = new SimpleDateFormat ("dd-MM-yyyy");
                    txtjam.setText(Jam.format(cal.getTime()));
                    txttanggal.setText(Tanggal.format(cal.getTime()));
                    try { sleep(1000);
                } catch (InterruptedException ex) {
                  Logger.getLogger(aplikasikasirujikom.FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                  }
                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formlogin = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cmbAkses = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        btnBatal = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPelanggan = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        txtjam = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        logout = new javax.swing.JMenu();
        register = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        produk = new javax.swing.JMenuItem();
        pelanggan = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        rkplap = new javax.swing.JMenuItem();
        tentang = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasikasir-MenuUtama");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formlogin.setTitle("Form Login");
        formlogin.setVisible(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-login-35 (1).png")); // NOI18N
        jLabel2.setText("LOGIN DISINI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-user-35 (1).png")); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-password-35 (2).png")); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-access-35.png")); // NOI18N
        jLabel5.setText("Hak Akses");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        cmbAkses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Salah Satu-", "Admin", "Petugas" }));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-delete-35.png")); // NOI18N
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMasuk.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-enter-35.png")); // NOI18N
        btnMasuk.setText("MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formloginLayout = new javax.swing.GroupLayout(formlogin.getContentPane());
        formlogin.getContentPane().setLayout(formloginLayout);
        formloginLayout.setHorizontalGroup(
            formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formloginLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername)
                    .addComponent(cmbAkses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(188, 188, 188))
            .addGroup(formloginLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnMasuk)
                .addGap(91, 91, 91))
        );
        formloginLayout.setVerticalGroup(
            formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formloginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnMasuk))
                .addGap(67, 67, 67))
        );

        getContentPane().add(formlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPelanggan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-customer-35.png")); // NOI18N
        btnPelanggan.setText("Pelanggan");
        jPanel3.add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 29, -1, -1));

        btnProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProduk.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-product-35.png")); // NOI18N
        btnProduk.setText("Produk");
        jPanel3.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 29, -1, -1));

        btnPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPenjualan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-sale-35.png")); // NOI18N
        btnPenjualan.setText("Penjualan");
        jPanel3.add(btnPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 29, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 580, 110));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-register-35 (1).png")); // NOI18N
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 544, -1, -1));

        lbluser.setText("silahkan login!!!");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 630));

        txtjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjamActionPerformed(evt);
            }
        });
        getContentPane().add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 33, 90, -1));
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 33, 96, -1));

        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-home-20.png")); // NOI18N
        logout.setText("Beranda");

        register.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-register-25 (1).png")); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        logout.add(register);

        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-logout-25.png")); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        logout.add(Logout);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-login-35 (1).png")); // NOI18N
        jMenuItem3.setText("Login");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        logout.add(jMenuItem3);

        jMenuBar1.add(logout);

        master.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-master-25.png")); // NOI18N
        master.setText("Master");

        produk.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-product-25.png")); // NOI18N
        produk.setText("Produk");
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        master.add(produk);

        pelanggan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-customer-25.png")); // NOI18N
        pelanggan.setText("Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        master.add(pelanggan);

        jMenuBar1.add(master);

        transaksi.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-transaction-25.png")); // NOI18N
        transaksi.setText("Transaksi");

        penjualan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-sale-25.png")); // NOI18N
        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        transaksi.add(penjualan);

        jMenuBar1.add(transaksi);

        laporan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-report-25.png")); // NOI18N
        laporan.setText("Laporan");

        rkplap.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-audit-25.png")); // NOI18N
        rkplap.setText("Rekap Laporan");
        rkplap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkplapActionPerformed(evt);
            }
        });
        laporan.add(rkplap);

        jMenuBar1.add(laporan);

        tentang.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-about-25.png")); // NOI18N
        tentang.setText("Help");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-about-25.png")); // NOI18N
        jMenuItem1.setText("Tentang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        tentang.add(jMenuItem1);

        jMenuBar1.add(tentang);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        new MenuUtama().setVisible(true);                // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        try {
            String sql = "select * from login where Username='"+txtUsername.getText()+"' and Password='"+txtPassword.getText()+"' and HakAkses='"+cmbAkses.getSelectedItem()+"'";
            pst = konek.prepareStatement(sql);
            rst = pst.executeQuery();
            if (rst.next()) {
                if(txtUsername.getText().equals(rst.getString("username"))&& txtPassword.getText().equals(rst.getString("password"))&& cmbAkses.getSelectedItem().equals(rst.getString("HakAkses")));
                if(cmbAkses.getSelectedItem().equals("Admin")) {
                    register.setEnabled(true);
                    Logout.setEnabled(true);
                    master.setEnabled(true);
                    transaksi.setEnabled(true);
                    laporan.setEnabled(true);
                    btnRegister.setEnabled(true);
                    btnProduk.setEnabled(true);
                    btnPelanggan.setEnabled(true);
                    btnPenjualan.setEnabled(true);
                    txtjam.setEnabled(false);
                    txttanggal.setEnabled(false);
                    formlogin.setVisible(false);
                } else if (cmbAkses.getSelectedItem().equals("Petugas")) {
                    register.setEnabled(false);
                    Logout.setEnabled(true);
                    master.setEnabled(true);
                    transaksi.setEnabled(true);
                    laporan.setEnabled(true);
                    btnRegister.setEnabled(false);
                    btnProduk.setEnabled(true);
                    btnPelanggan.setEnabled(true);
                    btnPenjualan.setEnabled(true);
                    txtjam.setEnabled(false);
                    txttanggal.setEnabled(false);
                    formlogin.setVisible(false);

                }

                {
                    JOptionPane.showMessageDialog(null, "Selamat Datang'"+txtUsername.getText()+"'");
                    String text = txtUsername.getText();
                    lbluser.setText("Selamat Datang, "+text);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Gagal masuk. Periksa Kembali Username/Password/hak akses");
                txtUsername.setText("");
                txtPassword.setText("");
                cmbAkses.setSelectedItem("-Pilih Salah Satu-");
            }
        }catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Gagal Koneksi");// TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed
    }
    private void txtjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
new MenuUtama().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
 new formProduk().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_produkActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
new aplikasikasirujikom.FormRegister().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
formlogin.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
new aplikasikasirujikom.FormPelanggan().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_pelangganActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
new aplikasikasirujikom.FormPenjualan().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_penjualanActionPerformed

    private void rkplapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkplapActionPerformed
new LaporanTransaksi().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rkplapActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new FormAbout().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbAkses;
    private javax.swing.JInternalFrame formlogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu laporan;
    private javax.swing.JLabel lbluser;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JMenuItem produk;
    private javax.swing.JMenuItem register;
    private javax.swing.JMenuItem rkplap;
    private javax.swing.JMenu tentang;
    private javax.swing.JMenu transaksi;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
